### ISSUE TITLE
Add a justification as to why a user should use 'insecure-registries'

### ISSUE THREAD

**Issue by halfer** [fzuleta/private-docker-registry-ssl#3]
The existing text has this instruction:

> add your repo url to the insecure-registries

This sounds ominous, since the point of the tutorial is to set up a private Docker registry that is secure. I'm not saying your instructions are wrong (I don't have enough experience in this area to say), just that you may wish to explain why this instruction is correct.

**Comment by fzuleta** [comment]
it's not really needed :) I've updated the readme
thanks!
